### ISSUE TITLE
테스트 데이터 생성

### ISSUE THREAD

**Issue by crossbell8368** [card-monkey/card-monkey-BE#15]
## Description

* ERD 설계도를 기반으로 테스트용 Card 데이터(체크:50/신용:50) 생성
* 동일한 샘플정보 확보를 위해 카드고릴라 홈페이지에서 데이터 수집
* 월간 기준(20230101~20230131) 인기 체크 & 신용 카드 각각 50개씩 수집

## Tasks

- [x] 수집 데이터 저장용 스프레드 시트 구성
- [x] 신용카드 데이터 수집
- [x] 체크카드 데이터 수집
- [x] csv 파일 변환 후, sql 문으로 변환

## References

- [카드고릴라 월간 카드순위](https://www.card-gorilla.com/chart/top100?term=monthly&date=2023-01-01)
- [데이터 스프레드시트](https://docs.google.com/spreadsheets/d/1mYUjQwcVBon7SDW6I-z3sNVfkBldXMkIHxO1iya6o1I/edit?usp=sharing)

**Comment by flimberkim** [comment]
```sql
INSERT INTO card
(name, company, last_month_paid, annual_fee, card_type, imageurl, applyurl, coffee, transportation,movie,delivery,phone,gas,simple_payment,tax,shopping)
VALUES
('010PAY 체크카드'                ,'우리카드'     ,     0 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/765/card_img/25707/765card.png'   ,'https://ezauth.settlebank.co.kr/wooricard.do?utm_source=partner&utm_medium=int_gorilla_product&utm_campaign=cc_season2&utm_id=cc_season2' ,null  ,'yes' ,null  ,null  ,null  ,null  ,null  ,null  ,null)  ,
('PAYCO 포인트 카드'               ,'엔에이치엔페이코' ,     0 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/2310/card_img/23676/2310card.png' ,'https://www.card-gorilla.com/statics/html/payco_point.html'                                                                               ,null  ,null  ,null  ,null  ,null  ,null  ,null  ,null  ,'yes')   ,
('신한카드 Deep Dream 체크'         ,'신한카드'     ,     0 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/281/card_img/20503/281card.png'   ,'https://www.shinhancard.com/pconts/html/card/apply/check/1188313_2206.html?EntryLoc2=2873&empSeq=5&btnApp=K0L1K3'                         ,null  ,'yes' ,null  ,null  ,null  ,'yes' ,null  ,null  ,null)  ,
('네이버페이 우리카드 체크'              ,'우리카드'     ,     0 ,5000 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/588/card_img/21345/588card.png'   ,'https://dbill.naver.com/build/index.html#/partnership-card/woori'                                                                         ,null  ,null  ,null  ,null  ,null  ,null  ,null  ,null  ,null)  ,
('노리체크카드'                     ,'KB국민카드'   ,200000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/348/card_img/20581/348card.png'   ,'https://card.kbcard.com/CRD/DVIEW/HCAMCXPRICAC0137?cooperationcode=01664&solicitorcode=7030084000'                                        ,null  ,'yes' ,'yes' ,null  ,'yes' ,null  ,null  ,null  ,null)  ,
('NU 오하쳌(오늘하루체크)'             ,'우리카드'     ,200000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/762/card_img/26507/762card.png'   ,'https://pc.wooricard.com/dcpc/yh1/crd/crd01/H1CRD201S00.do'                                                                               ,'yes' ,'yes' ,null  ,'yes' ,'yes' ,null  ,'yes' ,null  ,'yes') ,
('노리2 체크카드(KB Pay)'           ,'KB국민카드'   ,200000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/2422/card_img/27141/2422card.png' ,'https://card.kbcard.com/CRD/DVIEW/HCAMCXPRICAC0076?mainCC=a&cooperationcode=07964&solicitorcode=7030084002'                               ,'yes' ,null  ,'yes' ,'yes' ,'yes' ,null  ,'yes' ,null  ,null)  ,
('카카오페이 신한 체크카드'              ,'신한카드'     ,     0 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/286/card_img/20508/286card.png'   ,'https://www.shinhancard.com/pconts/html/card/apply/check/1187963_2206.html?EntryLoc2=2940&empSeq=3'                                       ,null  ,'yes' ,'yes' ,null  ,'yes' ,null  ,null  ,null  ,null)  ,
('NH20해봄체크카드'                 ,'NH농협카드'   ,200000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/362/card_img/20603/362card.png'   ,'https://card.nonghyup.com/IpCc0001M.act'                                                                                                  ,null  ,null  ,null  ,null  ,null  ,null  ,null  ,null  ,'yes') ,
('네이버페이 머니 하나 체크카드'           ,'하나카드'     ,250000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/2432/card_img/27295/2432card.png' ,'https://new-m.pay.naver.com/paymoney/bankbook/pc'                                                                                         ,null  ,null  ,null  ,null  ,null  ,null  ,null  ,null  ,null)  ,
('토스뱅크카드'                     ,'토스뱅크'     ,     0 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/2269/card_img/20697/2269card.png' ,'https://www.tossbank.com/product-service/card/check-card'                                                                                 ,null  ,null  ,null  ,null  ,null  ,null  ,null  ,null  ,null)  ,
('라이언 치즈 체크카드'                ,'NH농협카드'   ,200000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/528/card_img/21216/528card.png'   ,'https://card.nonghyup.com/IpCc0001M.act'                                                                                                  ,'yes' ,'yes' ,'yes' ,'yes' ,null  ,null  ,null  ,null  ,'yes') ,
('카카오뱅크 프렌즈 체크카드'             ,'카카오뱅크'    ,     0 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/435/card_img/20935/435card.png'   ,'https://www.kakaobank.com/products/checkcard'                                                                                             ,null  ,null  ,null  ,null  ,null  ,null  ,null  ,null  ,null)  ,
('신한카드 Hey Young 체크'          ,'신한카드'     ,200000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/618/card_img/21385/618card.png'   ,'https://www.shinhancard.com/pconts/html/card/apply/check/1196867_2206.html?EntryLoc2=2998&empSeq=514&btnApp=dp1'                          ,'yes' ,'yes' ,'yes' ,null  ,'yes' ,null  ,'yes' ,null  ,'yes') ,
('신한카드 On 체크(잔망루피)'           ,'신한카드'     ,200000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/2379/card_img/25379/2379card.png' ,'https://www.shinhancard.com/pconts/html/card/apply/check/1216927_2206.html?EntryLoc2=3209&empSeq=507&btnApp=dp1'                          ,null  ,null  ,null  ,null  ,null  ,null  ,'yes' ,null  ,null)  ,
('직장인보너스체크카드'                 ,'KB국민카드'   ,200000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/350/card_img/20594/350card.png'   ,'https://card.kbcard.com/CRD/DVIEW/HCAMCXPRICAC0137?cooperationcode=01690&solicitorcode=7030084000'                                        ,null  ,'yes' ,null  ,null  ,'yes' ,'yes' ,null  ,'yes' ,'yes') ,
('알뜰교통카드 COOKIE CHECK'        ,'우리카드'     ,200000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/584/card_img/21328/584card.png'   ,'https://pc.wooricard.com/dcpc/yh1/cct/cct14/H1CCT214S02.do'                                                                               ,null  ,'yes' ,'yes' ,null  ,null  ,null  ,'yes' ,null  ,null)  ,
('위글위글 첵첵 체크카드'               ,'KB국민카드'   ,300000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/614/card_img/21381/614card.png'   ,'https://card.kbcard.com/CRD/DVIEW/HCAMCXPRICAC0137?cooperationcode=01918&solicitorcode=7030084000'                                        ,'yes' ,'yes' ,'yes' ,null  ,null  ,null  ,'yes' ,null  ,'yes') ,
('노리2 체크카드(Global)'           ,'KB국민카드'   ,200000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/2423/card_img/27142/2423card.png' ,'https://card.kbcard.com/CRD/DVIEW/HCAMCXPRICAC0076?mainCC=a&cooperationcode=07972&solicitorcode=7030084002'                               ,'yes' ,null  ,'yes' ,'yes' ,'yes' ,null  ,null  ,null  ,null)  ,
('신한카드 Deep Dream 체크(미니언즈)'   ,'신한카드'     ,     0 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/646/card_img/21410/646card.png'   ,'https://www.shinhancard.com/pconts/html/card/apply/check/1187959_2206.html?EntryLoc=2927&empSeq=558&btnApp=dp1'                           ,null  ,'yes' ,null  ,null  ,null  ,'yes' ,null  ,null  ,null)  ,
('카카오페이 KB국민 체크카드'            ,'KB국민카드'   ,300000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/332/card_img/20576/332card.png'   ,'https://card.kbcard.com/CRD/DVIEW/HCAMCXPRICAC0137?cooperationcode=01782&solicitorcode=7030084000'                                        ,'yes' ,'yes' ,null  ,null  ,null  ,null  ,null  ,null  ,null)  ,
('LoL CHAMPIONS KOREA 우리체크카드' ,'우리카드'     ,250000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/313/card_img/20558/313card.png'   ,'https://www.bccard.com/app/card/CreditCardMain.do?gdsno=836397'                                                                           ,'yes' ,null  ,'yes' ,null  ,null  ,null  ,null  ,null  ,'yes') ,
('신한카드 Deep Dream 체크(모베러웍스)'  ,'신한카드'     ,     0 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/2391/card_img/25864/2391card.png' ,'https://www.shinhancard.com/pconts/html/card/apply/check/1215762_2206.html?EntryLoc=3171&empSeq=502&btnApp=dp1'                           ,null  ,'yes' ,null  ,null  ,null  ,'yes' ,null  ,null  ,null)  ,
('Liiv Mate 체크카드'             ,'KB국민카드'   ,300000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/333/card_img/20577/333card.png'   ,'https://card.kbcard.com/CRD/DVIEW/HCAMCXPRICAC0137?cooperationcode=01976&solicitorcode=7030084000'                                        ,'yes' ,'yes' ,'yes' ,null  ,'yes' ,null  ,null  ,null  ,null)  ,
('청춘대로 싱글 체크카드'               ,'KB국민카드'   ,300000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/335/card_img/20579/335card.png'   ,'https://card.kbcard.com/CRD/DVIEW/HCAMCXPRICAC0137?cooperationcode=01988&solicitorcode=7030084000'                                        ,null  ,'yes' ,null  ,null  ,null  ,null  ,null  ,null  ,null)  ,
('알뜰교통 비바 e 플래티늄 체크카드'        ,'하나카드'     ,250000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/746/card_img/27830/746card.png'   ,'https://m.hanacard.co.kr/MPACMM101M.web?CD_PD_SEQ=12800'                                                                                  ,null  ,'yes' ,null  ,null  ,null  ,null  ,null  ,null  ,'yes') ,
('New 현대백화점 체크카드'             ,'우리카드'     ,200000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/331/card_img/20575/331card.png'   ,'https://www.bccard.com/app/card/CheckCardMain.do?gdsno=221944'                                                                            ,'yes' ,null  ,'yes' ,null  ,null  ,'yes' ,null  ,null  ,'yes') ,
('NH올원체크카드'                   ,'NH농협카드'   ,     0 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/368/card_img/20609/368card.jpg'   ,'https://card.nonghyup.com/IpCc0001M.act'                                                                                                  ,null  ,null  ,null  ,null  ,null  ,null  ,null  ,null  ,null)  ,
('올바른 NEW HAVE체크카드'           ,'NH농협카드'   ,     0 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/1765/card_img/22348/1765card.png' ,'https://card.nonghyup.com/IpCc0001M.act'                                                                                                  ,null  ,null  ,null  ,null  ,null  ,null  ,null  ,null  ,null)  ,
('카카오페이 신한 콘 체크카드'            ,'신한카드'     ,     0 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/670/card_img/21435/670card.png'   ,'https://www.shinhancard.com/pconts/html/card/apply/check/1198442_2206.html?EntryLoc2=3010&empSeq=1'                                       ,null  ,null  ,null  ,null  ,null  ,null  ,null  ,null  ,null)  ,
('쏘영 체크카드'                    ,'KB국민카드'   , 50000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/680/card_img/21445/680card.png'   ,'https://card.kbcard.com/CRD/DVIEW/HCAMCXPRICAC0076?cooperationcode=01570&mainCC=a'                                                        ,null  ,'yes' ,null  ,null  ,null  ,null  ,null  ,null  ,'yes') ,
('펭수 노리 체크카드(펭모티콘)'           ,'KB국민카드'   ,200000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/561/card_img/21266/561card.png'   ,'https://card.kbcard.com/CRD/DVIEW/HCAMCXPRICAC0137?cooperationcode=01904&solicitorcode=7030084000'                                        ,null  ,'yes' ,'yes' ,null  ,'yes' ,null  ,null  ,null  ,null)  ,
('NEW농촌사랑체크카드'                ,'NH농협카드'   ,200000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/497/card_img/21186/497card.png'   ,'https://card.nonghyup.com/IpCc0001M.act'                                                                                                  ,null  ,null  ,null  ,null  ,null  ,'yes' ,null  ,null  ,null)  ,
('포인트리체크카드'                   ,'KB국민카드'   ,200000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/343/card_img/20588/343card.png'   ,'https://card.kbcard.com/CRD/DVIEW/HCAMCXPRICAC0137?cooperationcode=01556&solicitorcode=7030084000'                                        ,null  ,'yes' ,'yes' ,null  ,'yes' ,'yes' ,null  ,null  ,'yes') ,
('펭수 노리 체크카드(펭카)'             ,'KB국민카드'   ,200000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/559/card_img/21264/559card.png'   ,'https://card.kbcard.com/CRD/DVIEW/HCAMCXPRICAC0137?cooperationcode=01900&solicitorcode=7030084000'                                        ,null  ,'yes' ,'yes' ,null  ,'yes' ,null  ,null  ,null  ,null)  ,
('민 체크카드'                     ,'KB국민카드'   ,300000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/346/card_img/20591/346card.png'   ,'https://card.kbcard.com/CRD/DVIEW/HCAMCXPRICAC0137?cooperationcode=01560&solicitorcode=7030084000'                                        ,null  ,'yes' ,null  ,null  ,'yes' ,'yes' ,null  ,null  ,'yes') ,
('NU Uniq Check'              ,'우리카드'     ,300000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/2370/card_img/25307/2370card.png' ,'https://pc.wooricard.com/dcpc/main.do'                                                                                                    ,'yes' ,'yes' ,null  ,'yes' ,null  ,null  ,null  ,null  ,'yes') ,
('갤러리아 체크카드'                  ,'우리카드'     ,300000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/329/card_img/20573/329card.png'   ,'https://pc.wooricard.com/dcpc/main.do'                                                                                                    ,null  ,null  ,null  ,null  ,null  ,null  ,null  ,null  ,'yes') ,
('아시아나 체크카드'                  ,'KB국민카드'   ,300000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/334/card_img/20578/334card.png'   ,'https://card.kbcard.com/CRD/DVIEW/HCAMCXPRICAC0137?cooperationcode=01974&solicitorcode=7030084000'                                        ,'yes' ,null  ,null  ,null  ,null  ,null  ,null  ,null  ,'yes') ,
('카카오페이 체크카드'                 ,'MG새마을금고'  ,150000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/2094/card_img/21906/2094card.png' ,'http://www.ylmg.co.kr/sub5/s6.htm'                                                                                                        ,'yes' ,null  ,'yes' ,null  ,null  ,null  ,null  ,null  ,'yes') ,
('가온 올포인트 체크카드'               ,'KB국민카드'   ,100000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/454/card_img/20970/454card.png'   ,'https://card.kbcard.com/CRD/DVIEW/HCAMCXPRICAC0137?cooperationcode=01998&solicitorcode=7030084000'                                        ,'yes' ,'yes' ,null  ,null  ,'yes' ,'yes' ,null  ,null  ,'yes') ,
('신한카드 4Tune 체크'              ,'신한카드'     ,     0 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/290/card_img/20513/290card.png'   ,'https://www.shinhancard.com/pconts/html/card/check/MOBFM282R11.html'                                                                      ,'yes' ,null  ,null  ,null  ,null  ,null  ,null  ,null  ,null)  ,
('FANtastic S 신한카드 체크'        ,'신한카드'     ,300000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/278/card_img/20500/278card.png'   ,'https://www.shinhancard.com/pconts/html/card/check/MOBFM282R11.html'                                                                      ,'yes' ,null  ,null  ,null  ,null  ,null  ,'yes' ,null  ,'yes') ,
('새로이 체크카드'                   ,'KB국민카드'   ,300000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/725/card_img/22199/725card.png'   ,'https://card.kbcard.com/CRD/DVIEW/HCAMCXPRICAC0076?cooperationcode=01774&mainCC=a&solicitorcode=7020084000'                               ,'yes' ,null  ,null  ,null  ,'yes' ,null  ,null  ,null  ,null)  ,
('ONE 체크카드'                   ,'KB국민카드'   ,100000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/337/card_img/20582/337card.png'   ,'https://card.kbcard.com/CRD/DVIEW/HCAMCXPRICAC0137?cooperationcode=01946&solicitorcode=7030084000'                                        ,null  ,'yes' ,null  ,null  ,'yes' ,null  ,null  ,null  ,null)  ,
('신협 어부바 체크카드'                ,'신협'       ,200000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/1463/card_img/20611/1463card.jpg' ,'https://openbank.cu.co.kr/'                                                                                                               ,'yes' ,null  ,'yes' ,null  ,'yes' ,null  ,null  ,null  ,null)  ,
('내일배움체크카드'                   ,'NH농협카드'   ,     0 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/367/card_img/20608/367card.png'   ,'https://card.nonghyup.com/IpCc0001M.act'                                                                                                  ,null  ,null  ,'yes' ,null  ,null  ,'yes' ,null  ,null  ,'yes') ,
('카드의 정석 SSO3 NEW-TRO CHECK'  ,'우리카드'     ,300000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/656/card_img/21419/656card.png'   ,'https://pc.wooricard.com/dcpc/yh1/crd/crd01/H1CRD201S00.do'                                                                               ,null  ,'yes' ,null  ,null  ,null  ,null  ,null  ,null  ,'yes') ,
('콕체크카드'                      ,'NH농협카드'   ,     0 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/361/card_img/20602/361card.png'   ,'https://card.nonghyup.com/IpCc0001M.act'                                                                                                  ,null  ,null  ,null  ,null  ,null  ,null  ,null  ,null  ,'yes') ,
('탐나는전 체크카드'                  ,'KB국민카드'   ,100000 ,   0 ,'CHECK' ,'https://api.card-gorilla.com:8080/storage/card/1572/card_img/22656/1572card.png' ,'https://card.kbcard.com/CRD/DVIEW/HCAMCXPRICAC0076?mainCC=a&cooperationcode=01588&solicitorcode=7030084002'                               ,null  ,'yes' ,null  ,null  ,'yes' ,null  ,null  ,null  ,null);
```
체크카드 테스트데이터 insert문 입니다.

**Comment by crossbell8368** [comment]
## 테스트데이터 csv 파일
[CardMonkey_testData.csv](https://github.com/card-monkey/card-monkey-BE/files/10731248/CardMonkey_testData.csv)

**Comment by crossbell8368** [comment]
## 테스트데이터 insert SQL 파일

* cardmonkey 데이터베이스 사용 ( 테스트 시 변경필요 )
* 수행 시 card 테이블이 존재하면 drop 후 데이터 insert

[테스트데이터 SQL 파일](https://3-hks2188.slack.com/files/U04NKNC2KRQ/F04PEB3PL3F/cardmonkey_testdata.sql)
