### ISSUE TITLE
일부 엔티티 필드 추가 및 not null 설정

### ISSUE THREAD

**Issue by yunki-kim** [card-monkey/card-monkey-BE#18]
## Description

엔티티 필드 값 추가 필요 및 not null 설정 필요

## Tasks

- [x] Benefit 엔티티 tax, shopping 필드 추가
- [x] Card 엔티티 일부 `nullable=false` 설정
- [x] Member 엔티티 name 필드 추가, 일부 `nullable=false` 설정

**Comment by yunki-kim** [comment]
PR: #19 

작업 완료로 closed 처리
