### ISSUE TITLE
엔티티 수정

### ISSUE THREAD

**Issue by yunki-kim** [card-monkey/card-monkey-BE#6]
## Description

구현한 엔티티 중 수정이 필요한 엔티티가 있어 협의 후 엔티티 수정을 하고자함

## Tasks

- [x] Card 엔티티 description 필드 삭제
- [x] Review 엔티티 구조 변경 (별도의 comment 테이블 생성 및 연관관계 설정)
- [x] Member 엔티티 userId 필드 값 유니크 설정

**Comment by yunki-kim** [comment]
PR: #8 

작업 완료로 closed 처리
