### ISSUE TITLE
ERD 다이어그램 구성

### ISSUE THREAD

**Issue by crossbell8368** [card-monkey/card-monkey-BE#7]
## Description

* **20230210 : 1차 Entity 미팅**
  * 생성협의 테이블 
  * 회원(Member) / 찜목록(Favor) / 찜카드(FavorCard) / 신청목록(Paid) / 신청카드(PaidCard) / 한줄리뷰(Review) / 카드(Card)
  * 엔터티 생성 & ERD 테이블 구성도 작업 동시진행
  * 찜 & 신청 테이블의 경우, 하나의 테이블로 구성하게 될 경우 다대다 관계로 인해 관리 및 컨트롤의 어려움이 있을거으로 예상
  * 이에 목록과 정보를 이원화하여 중간에 버퍼 테이블구성, 다대다 관계를 해소

* **20230212 : 2차 Entity 미팅**
  * JPA기반 Entity 구성 및 연결,상속에 따른 테이블 형태 공유
  * Entity 기반 관계도 작성 & Entity 구성에 맞춰 ERD 테이블 구성도 수정
  * Review 테이블의 경우, 변수명의 설정 및 다중선택 등의 문제로 추가협의 예정

* **20230213 : 3차 Entity 미팅**
  * 한줄리뷰(Review) 테이블의 경우, 코멘트들을 저장하는 별도의 테이블을 구성
  * 사용자가 등록한 리뷰값에 코멘트 테이블의 값을 매핑하는 방식으로 우선 협의

## Tasks

- [x] ERD 관계도 초안작성
- [x] Entity 협의 & ERD 관계도 수정
- [x] 최종 ERD 테이블 관계도 작성

## References

- [1차 Entity 미팅 spreadsheets](https://docs.google.com/spreadsheets/d/1S5CW5CxalT1PXBnGEtPSeI6YMFG-P5YBwwJjQuDOwW8/edit?usp=sharing)
- [ERD 관계도 초안](https://3-hks2188.slack.com/files/U04NKNC2KRQ/F04P9NXKGLC/kdt3_cardmonkey.png)

**Comment by crossbell8368** [comment]
## 20230213 : 혜택추가
* 기존 7개 => 9개로 증가
* tax / shopping 추가

**Comment by crossbell8368** [comment]
## 20230216 : Entity 변경사항 적용

* PaidCard & FavorCard (버퍼테이블) 제거
* Token 테이블 추가

**Comment by crossbell8368** [comment]
## 20230224 : 최종안
* Review 기능 제거에 따른 관련 테이블 삭제 적용
* member 테이블에 name 컬럼 (프로필 이름) 추가
